sonar.projectKey=juanka588_cv_juan
sonar.projectName=CV_page
sonar.organization=juanka588
sonar.projectVersion=2.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
