sonar.projectKey=juanka588_cv_juan
sonar.projectName=CV_page
sonar.organization=juanka588
sonar.projectVersion=2.0

sonar.sources=.
sonar.tests=test
sonar.exclusions=build/**, node_modules/**, js/libs/**, font/**, images/**, css/nouislider.min.css, package-lock.json

sonar.javascript.lcov.reportPaths=build/coverage/lcov.info

sonar.sourceEncoding=UTF-8
